// Auto-generated by export_gait.py from RL training
// Model: checkpoints/best/best_model.zip
// Gait period: 20 steps (1.00s)
// Keyframes: 16
//
// IMPORTANT: The servo direction mapping (SERVO_DIRECTION) may need
// calibration for your specific robot build. If the robot walks
// incorrectly, try flipping the sign for individual joints in
// export_gait.py's SERVO_DIRECTION array.

inline void runLearnedWalkPose() {
  Serial.println(F("LEARNED WALK"));
  setFaceWithMode("walk", FACE_ANIM_ONCE);

  for (int i = 0; i < walkCycles; i++) {
    // Frame 1/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 2/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 3/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 4/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 5/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 6/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 7/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 8/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 9/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 10/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 11/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 12/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 13/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 14/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 15/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
    // Frame 16/16
    setServoAngle(R1, 137); setServoAngle(R2, 41); setServoAngle(L1, 45); setServoAngle(L2, 135);
    setServoAngle(R3, 178); setServoAngle(R4, 1); setServoAngle(L3, 0); setServoAngle(L4, 180);
    if (!pressingCheck("forward", frameDelay)) return;
  }
  runStandPose(1);
}
