[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
board_upload.flash_size = 32MB
board_build.flash_mode = dio
framework = espidf
upload_port = /dev/ttyACM1
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = -D CONFIG_IDF_TARGET_ESP32S3=1